# Generated by Django 5.2.6 on 2026-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
